spring:
  application:
    name: s3uploader

  servlet:
    multipart:
      max-file-size:    200MB
      max-request-size: 200MB

  datasource:
    url: jdbc:h2:mem:s3uploader

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console
